#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend iNtoko.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 292062-web-01 54.146.66.63
        server 292062-web-02 52.86.38.84
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
